### ISSUE TITLE
Headline is half covered

### ISSUE THREAD

**Issue by MarteSH** [automat-berlin/automat-berlin.github.io#1]
after choosing Factory or workshop there are situations where the respective headline is covered by the main menu element
![Bildschirmfoto 2019-05-24 um 09 43 36](https://user-images.githubusercontent.com/7382983/58311294-e8acfd00-7e08-11e9-9481-d8ca43312b23.png)
![Bildschirmfoto 2019-05-24 um 09 43 25](https://user-images.githubusercontent.com/7382983/58311313-f06ca180-7e08-11e9-9896-018071fea2ab.png)

**Comment by s-schumann** [comment]
On iPad, when jumping to factory/workshop, I also saw it being aligned too high (not covered but the text was too close to the grey header bar.

**Comment by shadzik** [comment]
Fixed
