### ISSUE TITLE
Compulsory statement for imprint

### ISSUE THREAD

**Issue by MarteSH** [automat-berlin/automat-berlin.github.io#2]
pls add at the beginning of imprint the following:

Compulsory statement
Compulsory Statement according § 35a GmbHG (Limited Liability Companies Act)
Automat Berlin GmbH

Handelsregister/Commercial Register: Berlin (AG Charlottenburg) HRB 203675
Sitz/Registered Office: Berlin, Deutschland/Germany
Geschäftsführer/Managing Director: Marten Schönherr, Dr.-Ing.

**Comment by barinali** [comment]
resolved in https://github.com/automat-berlin/automat-berlin.github.io/pull/20
