### ISSUE TITLE
Font size of bold headlines is smaller than text (specific resolutions only)

### ISSUE THREAD

**Issue by MarteSH** [automat-berlin/automat-berlin.github.io#4]
in factory and workshop there are resolutions where the headlines are smaller than the text
![Bildschirmfoto 2019-05-24 um 13 26 22](https://user-images.githubusercontent.com/7382983/58324681-d9897780-7e27-11e9-8510-38beff7d08e7.png)

**Comment by shadzik** [comment]
Fixed
