### ISSUE TITLE
Orange markers on iPad

### ISSUE THREAD

**Issue by s-schumann** [automat-berlin/automat-berlin.github.io#6]
The orange markers are part of the website's visual appearance.

The vertical alignment looks wrong on my iPad.

Device: iPad Pro 12.9'
Browser: Safari, landscape view

![Image from iOS (1)](https://user-images.githubusercontent.com/428710/58374644-eac6a700-7f41-11e9-8b83-823ae4d5ab61.jpg)

Discussion reference: https://automat-berlin.slack.com/archives/GGAM9764U/p1558681778001800

**Comment by shadzik** [comment]
This is a known issue. `background-attachment: fixed` is apparently disabled on mobile browsers for performance reasons.

Please see: https://stackoverflow.com/questions/23236158/how-to-replicate-background-attachment-fixed-on-ios
